### ISSUE TITLE
Metadata templating

### ISSUE THREAD

**Issue by azubieta** [azubieta/appimages.scraper#1]
Currently we have a problem at https://appimage.github.io/ the information (description, icon, scrennshots and so) about each application is very limited.
I was thinking that we can create templates of such projects in order to allow community members to contribute (by means of PR) to fill it.

There is a draft of my proposal in the project [readme](https://github.com/azubieta/appimages.scraper/blob/master/README.md#input). You can clone the project and test it. Please keep in mind that it is still under development.

@probonopd @TheAssassin I wold like to hear your thoughts about this topic.

**Comment by probonopd** [comment]
Any and all information needs to come from inside the AppImage, or from the location where the AppImage is downloaded from. No additional data should be maintained in AppImageHub. All data should be maintained by the respective upstream authors of the AppImage.

This ensures that all relevant metadata a) travels inside the AppImage along with the rest and b) does not have to be maintained in a central location.

**Comment by azubieta** [comment]
Totally agreed with you.
But take for example the case were the developer was to lazy to properly
include a all the data that an user would need. This is the case for most
of the apps we currently have listed at appimagehub.
The idea is to have a fallback mechanisms. Theese community edited
templates could be used by the authors latter to generate AppStream files.

**Comment by TheAssassin** [comment]
Perhaps you can convince users to send PRs to those people to add AppStream data? Of course, that doesn't always work, e.g., when they're not using GitHub. But it's a start.

**Comment by azubieta** [comment]
That would work too, as you said in some cases.
The feature is already implemented I'm not planning to make it the default
way of gattering information from the appimage files but to use it as a
fallback mechanism.

**Comment by probonopd** [comment]
> But take for example the case were the developer was to lazy to properly include a all the data that an user would need.

I have always had positive experiences with sending PRs (GitHub) or MRs (GitLab) to the respective upstream projects. So I agree with @TheAssassin that this should be the way to go.

**Comment by TheAssassin** [comment]
@probonopd please don't forget the other half of my statement, where I explain that this won't work in a lot of cases, e.g., when the software is not developed on github, or the scripts aren't open source.
